#+title: README
#+author: HMP
#+date: <2023-09-01 Fri>

** About
This repository is the club website for the Corner Stone club in Pacifica.
If the domain is up, it will be at https://pacificacornerstone.com.
** About Me
I am going to be the honorary secretary/tech consultant for the cornerstone club.
** Tech Stack
If the anyone in the club want to modify this website, then they would have to know javascript, typescript, and the NextJS web framework with the App Router. They must also understand basic GraqhQL operations that is connected to SANITY.
** Porting Environment Variables
#+BEGIN_SRC sh
NEXT_PUBLIC_GRAPHQL_URL=...
GOOGLE_CLIENT_ID=...
GOOGLE_CLIENT_SECRET=...
#+END_SRC
Paste the GraphQL URL of Sanity into this environment variable. And everything should work.
** Tasks
*** TODO Pacifica Cornerstone website
- [X] React-youtube responsiveness by applying css to iframe (15 min)
- [X] Meeting notes sub section progress bar (30 min)
- [X] Authenticated pages (meetings and schedules). The meetings page should be a carbon copy of the sub section but more links. (15 min)
- [ ] Setting up Sanity project schema. (1h) (clone of meetings)
- [ ] Connect meetings with Sanity. (1.5h) (clone of meetings)
- [ ] Connect Theological Questions with Sanity. (1h) (clone of meetings)
- [ ] Connect Writing Press with Sanity. (30 min) (clone of meetings)
- [ ] Google project and credentials to include all Pacifica Clubs (just authentication) (5 min)
- [ ] Finalize front-end responsiveness (2-5h)
- [ ] VC with Ian to connect the site with the domain. (1-4h)
