import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="w-screen flex flex-col lg:flex-row bg-red bg-[#952004] p-5 h-[179px]">
          <div className="m-auto flex flex-col lg:flex-row space-x-14">
            <div>
              <ul className="flex flex-col">
                <li className="text-4xl text-[#00a9ff]">Pacifica GGUSD</li>
                <li className="text-4xl text-white">Corner Stone</li>
              </ul>
            </div>
            <div className="flex flex-col space-y-4">
              <ul className="flex flex-col lg:flex-row lg:space-x-10">
                <li>
                  <Link className="hover:underline text-4xl" href="/mission">
                    Mission
                  </Link>
                </li>
                <li>
                  <Link className="hover:underline text-4xl" href="/members">
                    Members
                  </Link>
                </li>
                <li>
                  <Link className="hover:underline text-4xl" href="/schedule">
                    Schedule
                  </Link>
                </li>
                <li>
                  <Link className="hover:underline text-4xl" href="/meeting">
                    Meeting
                  </Link>
                </li>
              </ul>
              <ul className="flex flex-col lg:flex-row lg:space-x-10">
                <li>
                  <Link
                    className="hover:outline outline-2 bg-[#f40707] text-2xl p-1 px-2 rounded"
                    href="/theological-questions"
                  >
                    Theological Questions
                  </Link>
                </li>
                <li>
                  <Link
                    className="hover:outline outline-2 bg-[#f40707] text-2xl p-1 px-2 rounded"
                    href="/writing-press"
                  >
                    Writing Press
                  </Link>
                </li>
                <li>
                  <Link
                    className="hover:outline outline-2 bg-[#f40707] text-2xl p-1 px-2 rounded"
                    href="/signin"
                  >
                    Sign In
                  </Link>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
